version: "3"

services:
  mysqldb:
    image: mysql:8.0.43
    container_name: apisenhas-mysql
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_TCP_PORT=$MYSQL_DOCKER_PORT
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      - $MYSQL_DOCKER_PORT
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    # . siguifinica que o arquivo dockerfile esta nessa mesma pasta
    build: .
    working_dir: /usr/app
    container_name: apisenhas-app
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_LOCAL_PORT=$MYSQL_DOCKER_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    # porta utilizadas na aplicação
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    # comando de  start
    command: npm start

    # volume é para que seja copiado os arquivos em tempo real para a pasta do servidor
    volumes:
      - .:/usr/app
